title: 'Green Career Guide'
default_lang: en
author:
  name: 'Shaughn Dolcy'
  email: sdolcy@thehopeprogram.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Green Career Guide'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
